-- begin TESTTASK_REQUEST
alter table TESTTASK_REQUEST add constraint FK_TESTTASK_REQUEST_ON_CUSTOMER foreign key (CUSTOMER_ID) references TESTTASK_CUSTOMER(ID)^
alter table TESTTASK_REQUEST add constraint FK_TESTTASK_REQUEST_ON_SUPPLIER foreign key (SUPPLIER_ID) references TESTTASK_SUPPLIER(ID)^
create index IDX_TESTTASK_REQUEST_ON_CUSTOMER on TESTTASK_REQUEST (CUSTOMER_ID)^
create index IDX_TESTTASK_REQUEST_ON_SUPPLIER on TESTTASK_REQUEST (SUPPLIER_ID)^
-- end TESTTASK_REQUEST
-- begin TESTTASK_REQUEST_ITEM
alter table TESTTASK_REQUEST_ITEM add constraint FK_TESTTASK_REQUEST_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references TESTTASK_PRODUCT(ID)^
alter table TESTTASK_REQUEST_ITEM add constraint FK_TESTTASK_REQUEST_ITEM_ON_REQUEST foreign key (REQUEST_ID) references TESTTASK_REQUEST(ID) on delete CASCADE^
create index IDX_TESTTASK_REQUEST_ITEM_ON_PRODUCT on TESTTASK_REQUEST_ITEM (PRODUCT_ID)^
create index IDX_TESTTASK_REQUEST_ITEM_ON_REQUEST on TESTTASK_REQUEST_ITEM (REQUEST_ID)^
-- end TESTTASK_REQUEST_ITEM
