alter table TESTTASK_REQUEST_ITEM add constraint FK_TESTTASK_REQUEST_ITEM_ON_PRODUCT foreign key (PRODUCT_ID) references TESTTASK_PRODUCT(ID);
alter table TESTTASK_REQUEST_ITEM add constraint FK_TESTTASK_REQUEST_ITEM_ON_REQUEST foreign key (REQUEST_ID) references TESTTASK_REQUEST(ID);
create index IDX_TESTTASK_REQUEST_ITEM_ON_PRODUCT on TESTTASK_REQUEST_ITEM (PRODUCT_ID);
create index IDX_TESTTASK_REQUEST_ITEM_ON_REQUEST on TESTTASK_REQUEST_ITEM (REQUEST_ID);
